import { Injectable } from '@nestjs/common';
import { calendar_v3 } from 'googleapis';

@Injectable()
export class GoogleCalendarService {
  private adjustDateTime(dateTime: string): string {
    const date = new Date(dateTime);
    // Subtract 5 hours and 30 minutes (5:30)
    date.setHours(date.getHours() - 5);
    date.setMinutes(date.getMinutes() - 30);
    return date.toISOString();
  }
  async getEventByTitle(
    calendar: calendar_v3.Calendar,
    calendarId: string,
    title: string,
  ) {
    const res = await calendar.events.list({
      calendarId,
      q: title,
      singleEvents: true,
      maxResults: 10,
      orderBy: 'startTime',
    });

    const events = res.data.items ?? [];

    const matched = events.find((event) => event.summary === title);

    return matched || null;
  }

  async createEvent(
    calendar: calendar_v3.Calendar,
    calendarId: string,
    eventData: any,
  ) {
    console.log('Creating even: ', eventData);
    return calendar.events.insert({
      calendarId,
      requestBody: {
        summary: eventData.title,
        description: eventData.description || 'Generated by Reacter AI',
        start: {
          dateTime: this.adjustDateTime(eventData.startDateTime),
          timeZone: 'Asia/Kolkata',
        },
        end: {
          dateTime: this.adjustDateTime(eventData.endDateTime),
          timeZone: 'Asia/Kolkata',
        },
      },
    });
  }

  async updateEvent(
    calendar: calendar_v3.Calendar,
    calendarId: string,
    eventId: string,
    eventData: any,
  ) {
    return calendar.events.update({
      calendarId,
      eventId,
      requestBody: {
        summary: eventData.title,
        description: eventData.description || 'Updated by Reacter AI',
        start: {
          dateTime: this.adjustDateTime(eventData.startDateTime),
          timeZone: 'Asia/Kolkata',
        },
        end: {
          dateTime: this.adjustDateTime(eventData.endDateTime),
          timeZone: 'Asia/Kolkata',
        },
      },
    });
  }

  async deleteEvent(
    calendar: calendar_v3.Calendar,
    calendarId: string,
    eventId: string,
  ) {
    return calendar.events.delete({
      calendarId,
      eventId,
    });
  }
}
