import { Injectable } from '@nestjs/common';
import { calendar_v3 } from 'googleapis';

@Injectable()
export class GoogleCalendarService {
  async getEventByTitle(
    calendar: calendar_v3.Calendar,
    calendarId: string,
    title: string,
  ) {
    const res = await calendar.events.list({
      calendarId,
      q: title,
      singleEvents: true,
      maxResults: 10,
      orderBy: 'startTime',
    });

    const events = res.data.items ?? [];

    const matched = events.find((event) => event.summary === title);

    return matched || null;
  }

  async createEvent(
    calendar: calendar_v3.Calendar,
    calendarId: string,
    eventData: any,
    timezone: string = 'Asia/Kolkata',
  ) {
    console.log('Creating event: ', eventData);
    return calendar.events.insert({
      calendarId,
      requestBody: {
        summary: eventData.title,
        description: eventData.description || 'Generated by Reacter AI',
        start: {
          dateTime: new Date(eventData.startDateTime).toISOString(),
          timeZone: timezone,
        },
        end: {
          dateTime: new Date(eventData.endDateTime).toISOString(),
          timeZone: timezone,
        },
      },
    });
  }

  async updateEvent(
    calendar: calendar_v3.Calendar,
    calendarId: string,
    eventId: string,
    eventData: any,
    timezone: string = 'Asia/Kolkata',
  ) {
    return calendar.events.update({
      calendarId,
      eventId,
      requestBody: {
        summary: eventData.title,
        description: eventData.description || 'Updated by Reacter AI',
        start: {
          dateTime: new Date(eventData.startDateTime).toISOString(),
          timeZone: timezone,
        },
        end: {
          dateTime: new Date(eventData.endDateTime).toISOString(),
          timeZone: timezone,
        },
      },
    });
  }

  async deleteEvent(
    calendar: calendar_v3.Calendar,
    calendarId: string,
    eventId: string,
  ) {
    return calendar.events.delete({
      calendarId,
      eventId,
    });
  }
}
